name: taskflow
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^3.7.2
  dio: ^5.7.0
  flutter_dotenv: ^5.1.1
  google_fonts: ^6.2.1
  logger: ^2.4.0
  sizer: ^2.0.15
  skeletonizer: ^2.1.0+1
  flutter_spinkit: ^5.2.1
  custom_refresh_indicator: ^4.0.1
  font_awesome_flutter: ^10.7.0
  heroine: ^0.5.0+2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  syncfusion_flutter_datepicker: ^27.1.48
  toastification: ^3.0.3
  hive_ce_flutter: ^2.0.0
  freezed_annotation: ^3.1.0
  connectivity_plus: ^7.0.0
dev_dependencies:
  build_runner: ^2.4.5
  freezed: ^3.2.3
  hive_ce_generator: ^1.9.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^2.0.0
  golden_toolkit: ^0.15.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - .env

